server:
  port: 1010
  servlet:
    context-path: /api


#开发环境配置
spring:
  profiles:
    active: dev
  #devtools插件
  devtools:
    livereload:
      enabled: true #是否支持livereload
      port: 35729
    restart:
      enabled: true #是否支持热部署


  #文件上传相关设置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #数据源配置
  datasource:
    name: springboot
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #mysql驱动
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://127.0.0.1:3306/cdc?useAffectedRows=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&?zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      web-stat-filter:
        session-stat-enable: true
        #????
        principal-session-name: admin
        url-pattern: /*
        session-stat-max-count: 100000
        exclusions: '*.js,/*.gif,/*.jpg,/*.png,/*.css,/*.ico,/druid/*'
        enabled: true
        #????
        principal-cookie-name: admin
        profile-enable: true
      filters: stat,wall
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          log-violation: true
          db-type: mysql
          config:
            delete-allow: true
            truncate-allow: false
            drop-table-allow: false
          enabled: true
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 123456
        enabled: true

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dingding.cdc.entity
  configuration:
    # 使用jdbc的getGeneratedKeys 可以获取数据库自增主键值
    use-generated-keys: true
    # 使用列别名替换列名，默认true。如：select name as title from table
    use-column-label: true
    # 开启驼峰命名转换，如：Table(create_time) -> Entity(createTime)。不需要我们关心怎么进行字段匹配，mybatis会自动识别`大写字母与下划线`
    map-underscore-to-camel-case: true

---
spring:
  profiles:
    active: test
